feature #10 tests done successfully and snapshots added
Code-Sauce-Official/FitMate pull request #30
Opened 2021-06-11 14:14 UTC by KishkinJ10

## Description

<This PR is regarding a feature request #10 in which test have been done successfully to check sign IN and sign-up functionality and screenshots have been added>

## Related Issue

Fixes #10  

## Type of Contribution:

- [ ] Coding
- [ ] Testing
- [ ] Research
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [ ] I have read README.md and CONTRIBUTION.md

- [ ] My code/design follows the style/guidelines of this project.
- [ ] I have performed a self-review of my own code/design/documentation.
- [ ] I have commented my code, particularly in hard-to-understand areas(or gave a proper description about the design).

2021-06-12 08:12 UTC, SHITIZ-AGGARWAL commented
@KishkinJ10 Use the url of photos in <img src " ">

2021-06-12 08:14 UTC, SHITIZ-AGGARWAL requested changes
Also please give space between different lines

2021-06-13 19:40 UTC, KishkinJ10 commented
Sir please check the changes made :)

2021-06-15 10:27 UTC, Acash512 requested changes
Implement the following:
- Errors set on textfields like Email cannot be empty, constraints on password in Sign Up(like min 8 digits, special character etc)
- Tests for Resend verification email
- Tests for Forgot Password

2021-06-15 16:01 UTC, KishkinJ10 commented
Sir please check the changes.

2021-06-16 20:07 UTC, Acash512 reviewed
Also add tests for Confirm Password, also if email has already been verified a toast saying "Email address already verified" is displayed on clicking Resend Verification Email, for forgot password entering email address is mandatory, a toast is shown if email is empty

2021-06-16 20:07 UTC, Acash512 commented on Documentation/Testing/SignUpTesting.md
> +     _Expected Result_:  Password must contain atleast one special character and minimum 8 digits<br>
Password must also contain a letter and a digit

2021-06-16 20:08 UTC, SHITIZ-AGGARWAL commented
![image](https://user-images.githubusercontent.com/53532851/122284914-b7318d80-cf0b-11eb-9b05-153d0b95d903.png)

@KishkinJ10 Use the URL properly

2021-06-16 20:13 UTC, SHITIZ-AGGARWAL commented
@KishkinJ10 While working on testing issues, try to cover every possible test you can think of . The main motive is to see whether the feature is working positively for each and every scenario. **TRY CRASHING THE APP**

You can note down every possibility first and then make test cases based on that, this will help you to cover more scenarios.

2021-06-17 15:52 UTC, KishkinJ10 commented
@SHITIZ-AGGARWAL @Acash512  Sir I have added all the test which I could have thought of , sir mostly all the tests are covered . Sir please merge this PR :)

2021-06-18 10:59 UTC, SHITIZ-AGGARWAL approved these changes

2021-06-18 11:00 UTC, yatharthmago01 approved these changes

2021-06-18 11:00 UTC, Acash512 approved these changes
Also add tests for Confirm Password, also if email has already been verified a toast saying "Email address already verified" is displayed on clicking Resend Verification Email, for forgot password entering email address is mandatory, a toast is shown if email is empty

2021-06-18 11:02 UTC, merged

2021-06-18 11:02 UTC, SHITIZ-AGGARWAL commented
@KishkinJ10 good work

2021-06-18 11:10 UTC, KishkinJ10 commented
@SHITIZ-AGGARWAL @yatharthmago01 @Acash512 Thank you sir for guiding me.